### PR TITLE
chore: update reference ui to use nomios

### PR DESCRIPTION
**Pull request by satazor**

### CODE REVIEW

**Comment by satazor** [comment]
Do not merge yet, I need to update the concept paper + the images in the repo.

Waiting for @andreforsousa

**Comment by satazor** [comment]
This is ready!

**Comment by dominguesgm** [comment]
If i'm not mistaken, `nomios-concept_profile-page.png` still has IDM at the top left corner. Maybe we should change that image too before merging.

**Comment by satazor** [comment]
@dominguesgm nice catch! Fixed.

Will rebase with master.

**Pull request merged**
