### PR TITLE
Journey --> flow

### PR DESCRIPTION
**Pull request by meiqimichelle**
A user journey typically means another type of diagram (a user's emotional journey around solving a problem/completing an action). This seems like a more straightforward "here is what people will be able to do in this app".

### CODE REVIEW

**Comment by satazor** [comment]
This is outside of my expertise, perhaps @andreforsousa can clarify.

If we change to "flow", we need to also update the filename and perhaps other usages of that word/naming.

**Comment by meiqimichelle** [comment]
Here's the first part of this article has nice overview comparing the two artifacts, for reference: [User Journey Maps or User Flows, what to do first?](https://medium.com/sketch-app-sources/user-journey-maps-or-user-flows-what-to-do-first-48e825e73aa8)

**Comment by andreforsousa** [comment]
@meiqimichelle I believe we can go with `user-flow`. This would be the name for the comprehensive layouts for all the screens and further specs provided through the low-fi prototype under InVision.

**Comment by meiqimichelle** [comment]
@andreforsousa @satazor did you want me to look around for other places to change that naming/usage, or is that a quick thing to do on your end (since you know the codebase/wordbase 😉 )

**Comment by satazor** [comment]
If you could change the filename of the diagram, we could merge this. Then, we will take care of searching in other places and fixing them as well.

**Comment by satazor** [comment]
@meiqimichelle thanks for this PR. I've changed everything in https://github.com/ipfs-shipyard/pm-idm/commit/fabd7b6c6a670092bad55a27d3083ededc20b454.

**Pull request closed without merging**
